[package]
name = "mmv"
version = "1.0.1"
edition = "2021"
license = "0BSD"
description = "Mapped file moves"
repository = "https://git.sr.ht/~mango/mmv"
authors = ["Thomas Voss <mail@thomasvoss.com>"]

[dependencies]
cerm = "1.1.1"
itertools = "0.11.0"
lexopt = "0.1.0"
tempfile = "3.7.0"
